teacher = (
    '<b>Комиссия информационных технологи</b>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=1315">Ефимов Евгений Михайлович</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=1165">Зятикова Татьяна Юрьевна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=1164">Макаров Сергей Евгеньевич</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=1162">Колчанова Юлия Валерьевна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=1157">Репьев Егор Денисович</a>\n\n'

    '<b>Комиссия математических и естественно-научных дисциплин</b>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=1300">Божко Екатерина Николаевна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=255">Горбоносова Наталья Геннадиевна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=1209">Дождикова Галина Николаевна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=259">Зыкова Елена Ивановна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=262">Николаев Владимир Николаевич</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=263">Овчинникова Ирина Николаевна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=1301">Ткачук Иван Анатольевич</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=1315">Трофимова Ирина Алексеевна</a>\n\n'

    '<b>Комиссия технологических дисциплин</b>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=1310">Кицваидзе Светлана Викторовна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=1309">Воинкова Наталья Александровна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=858">Гилев Николай Сергеевич</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=856">Пинягина Светлана Григорьевна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=847">Пологова Елена Михайловна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=289">Кузнецова Наталья Генадьевна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=288">Тюрикова Татьяна Егоровна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=287">Полторацкая Татьяна Викторовна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=286">Перель Анастасия Александровна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=281">Коровина Алла Юрьевна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=280">Ивушкина Ирина Александровна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=279">Гонтарь Ольга Викторовна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=277">Промышленникова Екатерина Владимировна</a>\n\n'

    '<b>Комиссия учетно-экономических дисциплин</b>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=1311">Русских Наталья Николаевна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=1173">Ершова Олеся Сергеевна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=852">Мусинова Лола Хабибуллаевна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=851">Пухова Валентина Лукинична</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=298">Шувалова Ирина Александровна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=297">Спицкая Вера Геннадьевна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=296">Мякишева Наталья Михайловна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=293">Кукреш Оксана Николаевна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=291">Дьячкова Светлана Петровна</a>\n'
    
    '<b>Комиссия правовых дисциплин</b>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=842">Киселев Станислав Константинович</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=844">Мельникова Анастасия Михайловна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=241">Минина Оксана Владимировна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=243">Морозова Ольга Сергеевна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=242">Осина Лариса Владимировна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=557">Полетаева Екатерина Олеговна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=845">Пухова Ксения Андреевна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=588">Тимерова Ольга Равильевна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=846">Шешукова Татьяна Александровна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=1313">Шмелева Юлия Александровна</a>\n\n'

    '<b>Комиссия общегуманитарных дисциплин</b>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=245">Боровская Наталья Викторовна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=244">Герасимова Марина Николаевна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=247">Долгорукова Надежда Сергеевна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=1303">Зверева Наталья Владимировна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=1297">Кочетова Влада Владиславовна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=1298">Крестьянинов Алексей Иннокентьевич</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=249">Митряева Татьяна Алексеевна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=253">Неклеса Елена Германовна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=250">Рыбникова Юлия Викторовна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=251">Сорина Мария Викторовна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=246">Сурина Оксана Петровна</a>\n'
    '● <a href="https://nttek.ru/about/prepodavateli/komissi/komissiya-inform.php?ELEMENT_ID=1299">Ткаченко Марина Владимировна</a>\n'
)

about_bot = ('Бот НТТЭК расписание | @nttek_2is6_bot\n'
            '➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖\n'
            'Привет, этого бота написал студент Нижнетагильского Торгово-Экономического колледжа,\n'
            'Бубнов Александр. Группа 3-ИС-6 @Kinoki445.\n'
            'Бот будет дорабатываться и тут будут присутствовать баги, прошу если заметишь сообщи о них мне.\n'
            'Но сейчас ты можешь сделать следующее:\n'

            '\n1) Узнать пары.\n'
            '2) Узнать как зовут преподавателей и какие дисциплины они ведут.\n'

            '\n➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖➖\n'
            'Если вы хотите связаться с автором:\n')
